name: Dependabot auto-merge

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions: {}

jobs:
  dependabot-auto-merge:
    if: >-
      github.actor == 'dependabot[bot]' &&
      github.event.pull_request.user.login == 'dependabot[bot]'
    uses: abijith-suresh/workflows/.github/workflows/dependabot-auto-merge.yml@163055ac24b4169ae93ae05c5d7491b1cd5d96c7 # v0.6.0
    with:
      major-update-policy: compatible-majors
    permissions:
      contents: read
      pull-requests: read
    secrets:
      DEPENDABOT_AUTOMERGE_TOKEN: ${{ secrets.DEPENDABOT_AUTOMERGE_TOKEN }}
